FROM ansibleplaybookbundle/apb-base

LABEL "com.redhat.apb.version"="0.1.0"
LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IHhhbWFyaW4tYXBwLWFwYgpkZXNjcmlwdGlvbjogU2V0cyB1cCBh\
IFhhbWFyaW4gQXBwIHJlcHJlc2VudGF0aW9uLgpiaW5kYWJsZTogRmFsc2UKYXN5bmM6IG9wdGlv\
bmFsCnRhZ3M6IAogIC0gbW9iaWxlCm1ldGFkYXRhOgogIGRpc3BsYXlOYW1lOiBYYW1hcmluIEFw\
cAogIGNvbnNvbGUub3BlbnNoaWZ0LmlvL2ljb25DbGFzczogZm9udC1pY29uIGljb24teGFtYXJp\
bgogIGltYWdlVXJsOiAiaW1hZ2VzL2xvZ29zL3hhbWFyaW4uc3ZnIgogIGRvY3VtZW50YXRpb25V\
cmw6ICJodHRwOi8vZG9jcy5hZXJvZ2Vhci5vcmciCiAgc2VydmljZU5hbWU6IHhhbWFyaW4tYXBw\
CnBsYW5zOgogIC0gbmFtZTogZGVmYXVsdAogICAgZGVzY3JpcHRpb246IFNldHMgdXAgYSBYYW1h\
cmluIEFwcCByZXByZXNlbnRhdGlvbi4KICAgIGZyZWU6IFRydWUKICAgIG1ldGFkYXRhOiB7fQog\
ICAgcGFyYW1ldGVyczoKICAgIC0gbmFtZTogYXBwTmFtZQogICAgICByZXF1aXJlZDogVHJ1ZQog\
ICAgICBkZWZhdWx0OiBteWFwcAogICAgICB0eXBlOiBzdHJpbmcKICAgICAgdGl0bGU6IEFwcGxp\
Y2F0aW9uIE5hbWUKICAgIC0gbmFtZTogYXBwSWRlbnRpZmllcgogICAgICByZXF1aXJlZDogVHJ1\
ZQogICAgICB0eXBlOiBzdHJpbmcKICAgICAgdGl0bGU6IFBhY2thZ2UgTmFtZQ=="

COPY playbooks /opt/apb/actions
COPY roles /opt/ansible/roles
COPY mobile /usr/bin
RUN chmod -R g=u /opt/{ansible,apb}
USER apb
